name: Build Action

on:
  push:
    branches: [main]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.github/workflows/build.yml'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.github/workflows/build.yml'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache libraries
        id: cache-libraries
        uses: actions/cache@v3
        with:
          path: ./build/_deps
          key: ${{ runner.os }}-libraries-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          cache: true

      - name: Configure CMake
        shell: bash
        run: cmake -B ./build -S .

      - name: Build Debug
        shell: bash
        run: cmake --build ./build --config Debug -j`nproc`

      - name: Build Release
        shell: bash
        run: cmake --build ./build --config Release -j`nproc`

  build-windows:
    name: Build on Windows
    needs: [build-linux]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache libraries
        id: cache-libraries
        uses: actions/cache@v3
        with:
          path: ./build/_deps
          key: ${{ runner.os }}-libraries-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install Qt (MinGW)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          arch: win64_mingw
          tools: mingw1120
          cache: true

      - name: Configure Debug
        shell: pwsh
        run: |
          cmake -S . -B build-debug `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build Debug
        shell: pwsh
        run: cmake --build build-debug -j"$env:NUMBER_OF_PROCESSORS"

      - name: Configure Release
        shell: pwsh
        run: |
          cmake -S . -B build-release `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        shell: pwsh
        run: cmake --build build-release -j"$env:NUMBER_OF_PROCESSORS"

  build-macos:
    name: Build on MacOS
    needs: [build-linux]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache libraries
        id: cache-libraries
        uses: actions/cache@v3
        with:
          path: ./build/_deps
          key: ${{ runner.os }}-libraries-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          cache: true

      - name: Configure CMake
        shell: bash
        run: cmake -B ./build -S .

      - name: Build Debug
        shell: bash
        run: cmake --build ./build --config Debug

      - name: Build Release
        shell: bash
        run: cmake --build ./build --config Release